### ISSUE TITLE
Set up Bamboo and Tomcat to be accessible from Laptop

### ISSUE THREAD

**Issue by dprof-johan** [dprof-johan/watch-my-rates#17]
## SubTasks
- [ ] Enable Remote Desktop to Media PC from Laptop
- [ ] Make sure Bamboo is available from Laptop using IP of Media PC
- [ ] Make sure Tomcat is available from Laptop using IP of Media PC
- [ ] Expose Tomcat webapps folder on Media PC over network to Laptop
