### ISSUE TITLE
Set up build and dev environment

### ISSUE THREAD

**Issue by dprof-johan** [dprof-johan/watch-my-rates#2]
- [x] Install GitBash on Laptop #8 
- [x] Install Java on Laptop
- [x] Install Eclipse STS on Laptop
- [x] Install GitBash on Media PC #9
- [x] Install Java on  Media PC #10
- [x] Install Eclipse STS on Media PC #11
- [x] Install Bamboo on Media PC #12
- [x] Install Tomcat on Media PC #15
- [x] Install Maven on Media PC #16
- [x] Install Maven on Laptop
- [x] Forbid push to master in GitHub #18

# Success Criteria:
* Both laptop and media PC have latest version of Java, and Git Bash and Eclipse/STS
* Media PC has Bamboo and Tomcat
