### ISSUE TITLE
Initial Setup

### ISSUE THREAD

**Issue by dprof-johan** [dprof-johan/watch-my-rates#3]
Collective Epic for getting started

# Success Criteria
- [x] Dev environment is working
- [x] Builds are automated
- [x] A Hello World Dojo webapp based on a RESTful service is running on Tomcat on the Media PC
