### ISSUE TITLE
As a WMR First time user, I want to easily create an account and sign up for better rates for my mortgage, so that I can get notified when there's something better for me

### ISSUE THREAD

**Issue by dprof-johan** [dprof-johan/watch-my-rates#30]
## SubTasks
- [ ] Task 1
- [ ] Task 2

## Success Criteria
- [ ] User can create new account by specifying email address and pwd
- [ ] User can enter simple mortgage to track
- [ ] User gets notified via email when better offer exists
