### ISSUE TITLE
AS a WMR Administrator, I want to be able to manually enter mortgage solutions, so that they can be compared to user's settings for sending out rate watches

### ISSUE THREAD

**Issue by dprof-johan** [dprof-johan/watch-my-rates#32]
## SubTasks
- [ ] Task 1
- [ ] Task 2

## Success Criteria
- [ ] Can log on as Administrator and get access to Admin gui
- [ ] Admin gui has a section for listing / adding / editing mortgage solutions (very simple for now)
- [ ] WMR service matches user and mortgage solutions and sends out rate watches after the manual update
