### ISSUE TITLE
AS the WMR site, I need secure logon using forms that protects against cross site attacks, so that I can secure the entire site

### ISSUE THREAD

**Issue by dprof-johan** [dprof-johan/watch-my-rates#48]
## SubTasks
- [x] Set up basic in memory security using simple normal form
- [x] Make security use users in the database
- [x] Use a fancier Dojo based form instead (Won't do)

## Success Criteria
- [x] Spring Security is implemented
- [x] Cross Site is prevented
