### ISSUE TITLE
Design starting page for web site

### ISSUE THREAD

**Issue by dprof-johan** [dprof-johan/watch-my-rates#53]
## SubTasks
- [ ] Task 1
- [ ] Task 2

## Implementation Details
Example for how to get control of the security, connecting to a user service
http://kielczewski.eu/2014/12/spring-boot-security-application/
https://spring.io/blog/2014/05/23/preview-spring-security-test-web-security

## Success Criteria
- [x] Looks nice enough for now. Design to come later
- [x] Loads dojo
- [x] Options for logging in/out
- [x] Shows logged in user
